/**
 * js/ui/help.js
 * User guide / help overlay — Phase 6.
 *
 * Provides an in-app help panel that explains how to use Nostradamus.
 * Accessible via a ❓ button in the nav bar. The overlay is modal,
 * traps focus, and closes on Escape or click outside.
 *
 * No external dependencies.
 */

// ─── Help content definition ──────────────────────────────────

/**
 * @type {Array<{title: string, icon: string, body: string}>}
 */
const HELP_SECTIONS = [
  {
    title: 'Getting Started',
    icon: '🚀',
    body: `
      <p>Nostradamus runs entirely in your browser — no account needed. In <strong>Demo Mode</strong>
      (no API key configured), the app shows sample stock data and AI predictions so you can explore
      all features without signing up for anything.</p>
      <p>To switch to <strong>Live Mode</strong> with real market data, open <strong>Settings ⚙️</strong>
      and enter a free <a href="https://finnhub.io/register" target="_blank" rel="noopener noreferrer">Finnhub API key</a>.</p>
    `,
  },
  {
    title: 'Searching Stocks',
    icon: '🔍',
    body: `
      <p>Use the search bar at the top to look up any stock by symbol or company name (e.g. "AAPL" or "Apple").</p>
      <p>Results appear as you type. Click a suggestion to open the stock detail view, or click
      <strong>☆</strong> to add it to your Watchlist without opening the detail.</p>
    `,
  },
  {
    title: 'Reading Predictions',
    icon: '🔮',
    body: `
      <p>Each stock card shows an AI-generated prediction:</p>
      <ul>
        <li><strong>Direction</strong> — ▲ UP or ▼ DOWN relative to today's close</li>
        <li><strong>Change</strong> — Predicted dollar move (e.g. +$3.50)</li>
        <li><strong>Confidence</strong> — How confident the model is (0–100%)</li>
      </ul>
      <p>Predictions are generated by a TensorFlow.js LSTM neural network running entirely in your browser,
      using price history, volume, RSI, and MACD as features.</p>
      <p><em>⚠️ Not financial advice. Past prediction accuracy does not guarantee future performance.</em></p>
    `,
  },
  {
    title: 'Watchlist',
    icon: '⭐',
    body: `
      <p>Click the <strong>☆</strong> star button on any stock card or detail view to add it to your Watchlist.</p>
      <p>Navigate to the <strong>Watchlist</strong> tab in the nav bar to see all your starred stocks in one place.
      Your watchlist is saved in your browser's localStorage and persists between sessions.</p>
    `,
  },
  {
    title: 'Accuracy Dashboard',
    icon: '📊',
    body: `
      <p>Click the <strong>📊</strong> icon in the nav bar to open the Accuracy Dashboard.</p>
      <p>It shows:</p>
      <ul>
        <li><strong>Hit Rate</strong> — Percentage of correct UP/DOWN direction calls</li>
        <li><strong>MAE</strong> — Mean Absolute Error (average dollar prediction error)</li>
        <li><strong>Weekly trend chart</strong> — Accuracy improving over time?</li>
        <li><strong>Model versions</strong> — History of trained model versions with A/B champion selection</li>
      </ul>
      <p>You can also <strong>Export CSV</strong> here to download your full prediction history.</p>
    `,
  },
  {
    title: 'Training the AI Model',
    icon: '🧠',
    body: `
      <p>Open <strong>Settings ⚙️</strong> and scroll to the <strong>AI Model</strong> section.</p>
      <p>Click <strong>🧠 Train Model</strong> to run in-browser training using historical data.
      Training takes 30–120 seconds depending on your device. A progress bar shows epochs and loss.</p>
      <p>The trained model is saved to localStorage and used for all future predictions.
      If the new model is more accurate, it automatically replaces the current champion.</p>
    `,
  },
  {
    title: 'Sector Analysis',
    icon: '🏭',
    body: `
      <p>Click the <strong>🏭 Sectors</strong> button in the nav bar to see stocks grouped by industry sector.</p>
      <p>Each sector card shows the aggregate bullish/bearish sentiment based on the most recent prediction
      for each tracked symbol. The bar shows the ratio of UP vs DOWN calls.</p>
    `,
  },
  {
    title: 'News & Sentiment',
    icon: '📰',
    body: `
      <p>Open any stock's detail view (click a stock card) and scroll to the <strong>News</strong> section.</p>
      <p>Recent headlines are fetched from Finnhub and scored with a keyword-based sentiment analysis:
      <span style="color:#26d97f">😊 Positive</span>, <span style="color:#8b91a7">😐 Neutral</span>,
      or <span style="color:#f05c6e">😟 Negative</span>.</p>
      <p>In Demo Mode, sample news is shown. Connect a Finnhub API key for live headlines.</p>
    `,
  },
  {
    title: 'Sharing Predictions',
    icon: '🔗',
    body: `
      <p>On any stock detail view, click the <strong>Share</strong> button to share the current prediction.</p>
      <ul>
        <li><strong>🐦 Twitter/X</strong> — Opens a pre-filled tweet with the prediction details</li>
        <li><strong>📋 Copy Link</strong> — Copies a shareable text snippet to your clipboard</li>
      </ul>
    `,
  },
  {
    title: 'Offline Support (PWA)',
    icon: '📱',
    body: `
      <p>Nostradamus is a <strong>Progressive Web App (PWA)</strong>. You can install it on your phone
      or desktop via the browser's "Add to Home Screen" or install prompt.</p>
      <p>Once installed and visited at least once, the app shell and demo data are cached for offline use.
      When offline, a banner is shown and cached data is displayed.</p>
    `,
  },
  {
    title: 'API Keys & Privacy',
    icon: '🔑',
    body: `
      <p>API keys are stored <strong>only in your browser's localStorage</strong> — they are never sent
      to any Nostradamus server (there isn't one). Keys are transmitted only to the respective API
      providers (Finnhub, Twelve Data, Polygon.io) when making data requests.</p>
      <p>You can clear all keys at any time from <strong>Settings ⚙️ → Clear All Keys</strong>.</p>
    `,
  },
];

// ─── Module state ─────────────────────────────────────────────

/** @type {HTMLElement|null} */
let _overlay = null;
/** @type {HTMLElement|null} */
let _triggerEl = null;
/** @type {((e: KeyboardEvent) => void)|null} */
let _keyHandler = null;

// ─── Public API ───────────────────────────────────────────────

/**
 * Open the help overlay if it isn't already open.
 */
export function openHelp() {
  if (_overlay) return; // already open

  _triggerEl = document.activeElement;
  _overlay = _buildOverlay();
  document.body.appendChild(_overlay);
  document.body.style.overflow = 'hidden';

  requestAnimationFrame(() => {
    _overlay.removeAttribute('hidden');
    _overlay.querySelector('.help-overlay__close')?.focus();
  });

  _keyHandler = e => {
    if (e.key === 'Escape') closeHelp();
  };
  document.addEventListener('keydown', _keyHandler);
}

/**
 * Close and remove the help overlay.
 */
export function closeHelp() {
  if (!_overlay) return;
  if (_keyHandler) {
    document.removeEventListener('keydown', _keyHandler);
    _keyHandler = null;
  }
  _overlay.remove();
  _overlay = null;
  document.body.style.overflow = '';
  _triggerEl?.focus();
  _triggerEl = null;
}

// ─── DOM builder ──────────────────────────────────────────────

/**
 * Build the help overlay DOM element.
 * @returns {HTMLElement}
 */
function _buildOverlay() {
  const overlay = document.createElement('div');
  overlay.className = 'help-overlay';
  overlay.setAttribute('role', 'dialog');
  overlay.setAttribute('aria-modal', 'true');
  overlay.setAttribute('aria-label', 'Help & User Guide');
  overlay.hidden = true;

  overlay.innerHTML = `
    <div class="help-overlay__backdrop"></div>
    <div class="help-overlay__panel" role="document">
      <div class="help-overlay__header">
        <h2 class="help-overlay__title">❓ Help &amp; User Guide</h2>
        <button class="help-overlay__close" aria-label="Close help">✕</button>
      </div>
      <div class="help-overlay__body">
        <p class="help-overlay__intro">
          Welcome to <strong>Nostradamus 🔮</strong> — the AI Stock Oracle.<br/>
          Everything runs in your browser. No sign-up required.
        </p>
        <div class="help-sections">
          ${HELP_SECTIONS.map(s => `
            <details class="help-section">
              <summary class="help-section__summary">
                <span class="help-section__icon">${s.icon}</span>
                <span class="help-section__title">${s.title}</span>
              </summary>
              <div class="help-section__body">${s.body}</div>
            </details>
          `).join('')}
        </div>
      </div>
    </div>
  `;

  // Close button
  overlay.querySelector('.help-overlay__close')?.addEventListener('click', closeHelp);
  // Click outside panel
  overlay.querySelector('.help-overlay__backdrop')?.addEventListener('click', closeHelp);

  return overlay;
}
