# One-time setup: Cloudflare account login + named tunnel (pretty hostname) + Access instructions.
# Without a domain on Cloudflare, use -QuickOnly or skip; autonomous_loop keeps trycloudflare fallback.
param(
    [string]$Hostname = "",
    [string]$TunnelName = "nostradamus",
    [int]$Port = 8000,
    [switch]$QuickOnly,
    [switch]$SkipLogin,
    [switch]$SkipDns
)

$ErrorActionPreference = "Stop"
$RepoRoot = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
. (Join-Path $RepoRoot "scripts\lib\cloudflare_tunnel.ps1")

$CfExe = Get-CloudflaredExe
if (-not $CfExe) {
    Write-Host "Install cloudflared: winget install --id Cloudflare.cloudflared"
    exit 1
}

$cfDir = Join-Path $RepoRoot "data\cloudflare"
$configPath = Join-Path $RepoRoot "config\cloudflare.json"
$examplePath = Join-Path $RepoRoot "config\cloudflare.example.json"
$ymlRel = "data/cloudflare/config.yml"
$ymlPath = Join-Path $RepoRoot "data\cloudflare\config.yml"
$credPath = Join-Path $cfDir "$TunnelName.json"

New-Item -ItemType Directory -Force -Path $cfDir, (Split-Path $configPath) | Out-Null

if ($QuickOnly) {
    if (-not (Test-Path $configPath)) {
        Copy-Item $examplePath $configPath
        $j = Get-Content $configPath -Raw | ConvertFrom-Json
        $j.mode = "quick"
        $j | ConvertTo-Json -Depth 5 | Set-Content $configPath -Encoding UTF8
    }
    Write-Host "(setup) Quick tunnel mode. Run: .\scripts\start_megamind_tunnel.ps1"
    Write-Host "(setup) Stable pretty URL needs a domain on Cloudflare - see docs/cloudflare-tunnel.md"
    exit 0
}

Write-Host ""
Write-Host "=== Nostradamus Cloudflare tunnel setup ==="
Write-Host "Pretty URL needs: (1) free Cloudflare account, (2) domain on Cloudflare DNS (~10 USD/yr)."
Write-Host "Until then: random trycloudflare.com URL (works on your phone)."
Write-Host "Register: https://dash.cloudflare.com/?to=/:account/domains/register"
Write-Host ""

if (-not $SkipLogin) {
    $cert = Get-OriginCertPath
    if (-not $cert) {
        Write-Host "(setup) Opening browser for Cloudflare login (free account OK)..."
        & $CfExe tunnel login
        if (-not (Get-OriginCertPath)) {
            Write-Host "(setup) Login did not complete (cert.pem missing). Re-run without -SkipLogin."
            exit 1
        }
        Write-Host "(setup) Logged in."
    } else {
        Write-Host "(setup) Already logged in: $cert"
    }
}

if (-not $Hostname) {
    if (Test-Path $configPath) {
        try {
            $existing = (Get-Content $configPath -Raw | ConvertFrom-Json).hostname
            if ($existing -and $existing -notmatch 'YOUR_DOMAIN') { $Hostname = $existing }
        } catch { }
    }
}
if (-not $Hostname) {
    $Hostname = Read-Host "Enter full hostname (e.g. nostradamus.example.com) or press Enter to skip named tunnel"
}
if (-not $Hostname -or $Hostname -match 'YOUR_DOMAIN') {
    Write-Host "(setup) No hostname - saving quick-mode config. Re-run with -Hostname when you have a domain."
    @{
        mode = "quick"
        tunnelName = $TunnelName
        hostname = ""
        localPort = $Port
        configPath = $ymlRel
    } | ConvertTo-Json -Depth 5 | Set-Content $configPath -Encoding UTF8
    exit 0
}

$Hostname = $Hostname.Trim().ToLower() -replace '^https?://', '' -replace '/.*$', ''

$tunnelId = $null
$listJson = & $CfExe tunnel list -o json 2>$null
if ($LASTEXITCODE -eq 0 -and $listJson) {
    $tunnels = $listJson | ConvertFrom-Json
    $match = $tunnels | Where-Object { $_.name -eq $TunnelName } | Select-Object -First 1
    if ($match) {
        $tunnelId = $match.id
        Write-Host "(setup) Reusing tunnel $TunnelName ($tunnelId)"
    }
}
if (-not $tunnelId) {
    if (Test-Path $credPath) { Remove-Item $credPath -Force }
    Write-Host "(setup) Creating tunnel $TunnelName ..."
    $createOut = & $CfExe tunnel create $TunnelName --credentials-file $credPath -o json 2>&1 | Out-String
    if ($LASTEXITCODE -ne 0) {
        Write-Host $createOut
        exit 1
    }
    $created = ($createOut | ConvertFrom-Json)
    if ($created.id) { $tunnelId = $created.id }
    elseif ($created[0].id) { $tunnelId = $created[0].id }
    if (-not $tunnelId -and (Test-Path $credPath)) {
        $cred = Get-Content $credPath -Raw | ConvertFrom-Json
        $tunnelId = $cred.TunnelID
    }
}
if (-not $tunnelId) {
    Write-Host "(setup) Could not determine tunnel ID."
    exit 1
}

$credFile = (Resolve-Path $credPath).Path -replace '\\', '/'
$yaml = (
    "# Generated by setup_cloudflare_tunnel.ps1",
    "tunnel: $tunnelId",
    "credentials-file: $credFile",
    "",
    "ingress:",
    "  - hostname: $Hostname",
    "    service: http://127.0.0.1:$Port",
    "  - service: http_status:404"
) -join "`n"
Set-Content -Path $ymlPath -Value $yaml -Encoding UTF8
Write-Host "(setup) Wrote $ymlPath"

if (-not $SkipDns) {
    Write-Host "(setup) Routing DNS $Hostname -> tunnel..."
    & $CfExe tunnel route dns $TunnelName $Hostname 2>&1 | ForEach-Object { Write-Host $_ }
    if ($LASTEXITCODE -ne 0) {
        Write-Host "(setup) DNS route failed. Add the zone in Cloudflare first, then re-run with -SkipLogin -Hostname $Hostname"
    }
}

$publicUrl = "https://$Hostname"
@{
    mode = "named"
    tunnelName = $TunnelName
    hostname = $Hostname
    localPort = $Port
    configPath = $ymlRel
} | ConvertTo-Json -Depth 5 | Set-Content $configPath -Encoding UTF8

Publish-TunnelUrl -RepoRoot $RepoRoot -PublicUrl $publicUrl -RefreshMegamind
Write-Host "(setup) Public URL: $publicUrl"
Write-Host ""
Write-Host "=== Cloudflare Access (lock to you + guests) ==="
Write-Host "1. Open https://one.dash.cloudflare.com/ -> Access -> Applications -> Add"
Write-Host "2. Self-hosted | Domain: $Hostname | Path: all (use /* in dashboard)"
Write-Host "3. Policy: Allow | Emails: nicholas.naumann27@gmail.com (add others when sharing)"
Write-Host "4. Optional: Login method -> One-time PIN for friends without Microsoft"
Write-Host ""
Write-Host 'Start tunnel: scripts/start_megamind_tunnel.ps1 (or autonomous_loop with tunnelEnabled)'
